# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha_creación',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha_publicación',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='texto',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='título',
            new_name='title',
        ),
    ]
